import torch
from torch import Tensor


class MultiWaveform(torch.nn.Module):
    """
    Callable class for combining multiple components generated by a
    single-burst waveform generator (e.g. `SineGaussian`, `MorletGabor`)
    into one waveform, optionally rescaled to a target total hrss.

    Args:
        generator: Single-burst waveform generator to combine
        sample_rate: Sample rate of waveform
        duration: Duration of waveform
        norm: Whether to rescale the combined waveform to `hrss_tot`
    """

    def __init__(
        self,
        generator: torch.nn.Module,
        sample_rate: float,
        duration: float,
        norm: bool = True,
    ):
        super().__init__()
        self.generator = generator
        self.sample_rate = sample_rate
        self.duration = duration
        self.norm = norm

    def compute_hrss(self, plus: Tensor, cross: Tensor):
        dt = 1.0 / self.sample_rate
        return torch.sqrt(dt * torch.sum(plus**2 + cross**2, dim=-1))

    def forward(self, **parameters):
        hrss_tot = parameters.pop("hrss_tot")
        N = hrss_tot.shape[0]
        n_components = hrss_tot.shape[-1]
        hrss_tot = hrss_tot[:, 0]
        n_samples = int(self.sample_rate * self.duration)

        cross, plus = self.generator(**parameters)
        cross = cross.reshape((N, n_components, n_samples))
        plus = plus.reshape((N, n_components, n_samples))

        cross = cross.nansum(dim=1)
        plus = plus.nansum(dim=1)

        if self.norm:
            current_hrss = self.compute_hrss(plus, cross).clamp_min(1e-30)
            scale = (hrss_tot.view(-1) / current_hrss).view(-1, 1)
            cross = cross * scale
            plus = plus * scale

        return cross, plus
